---

- name: Pull latest version from git repository
  git: repo={{ git_repo }}
       dest={{ app_path }}
       version={{ git_branch }}
       update=yes
  tags: git

- name: ensure we have usbutils installed
  apt: pkg=usbutils

- name: creates the printer service
  tags: config
  template: src=printer_service.j2
            dest=/etc/init.d/printer_service
            mode=0755
  notify:
    - restart printer_service

- name: ensures printer service is enabled
  tags: printer
  service: name=printer_service
           enabled=yes
           state=restarted
